### ISSUE TITLE
Make the website responsive

### ISSUE THREAD

**Issue by aaryanporwal** [aaryanporwal/littlelink#1]
After we put the links in a table format, the layout shifted a bit and now everything except the table is off centered.
Check out the attached screenshot:
![Screenshot_2021-09-18-01-35-48-85_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/54525904/133847679-46630212-b06b-447b-b9fa-e0f18e0193c6.jpg).

**Comment by noam-y** [comment]
working on it :)

**Comment by aaryanporwal** [comment]
Alright, I'll assign this issue to you. Thanks ✨

**Comment by noam-y** [comment]
just a q- is there a particular reason for making it a two-row table? can i turn it into a one row if the user's screen is too narrow?

**Comment by aaryanporwal** [comment]
> just a q- is there a particular reason for making it a two-row table? can i turn it into a one row if the user's screen is too narrow?

No particular reason, go ahead with whatever looks good :)

**Comment by aaryanporwal** [comment]
Also I hope you meant 2 column table

**Comment by noam-y** [comment]
> Also I hope you meant 2 column table

:p ofc

**Comment by noam-y** [comment]
just made a pull req that solves the issue. tell me what you think! :)

**Comment by noam-y** [comment]
thank you so much for your help! tell me what you think.
